name: FockSystem
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.12.8
  - pip:
      - cython==3.0.11
      - ipython==9.0.2
      - jupyterlab==4.3.5
      - matplotlib==3.10.0
      - numpy==2.2.2
      - scipy==1.15.1
      - xarray==2025.1.2
      - tqdm==4.67.1
